name: pr

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install ldid
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus6
      - name: Build
        run: yarn install
      - name: Rename
        run: |
          mv astgen-linux-x64 astgen-linux
          mv astgen-macos-x64 astgen-macos
          mv astgen-macos-arm64 astgen-macos-arm
          mv astgen-win-x64.exe astgen-win.exe
      - name: Make executable
        run: |
          chmod +x astgen-macos
          chmod +x astgen-linux
          ldid -S astgen-macos-arm
          chmod +x astgen-macos-arm
