name: release

on:
  push:
    branches: [master, main]
    tags: ["*"]

concurrency: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install ldid
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus6
      - name: Get next release version (dry run)
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      - name: Build
        run: yarn install
      - name: Rename
        run: |
          mv astgen-linux-x64 astgen-linux
          mv astgen-linux-arm64 astgen-linux-arm
          mv astgen-macos-x64 astgen-macos
          mv astgen-macos-arm64 astgen-macos-arm
          mv astgen-win-x64.exe astgen-win.exe
      - name: Make executable
        run: |
          chmod +x astgen-macos
          chmod +x astgen-macos-arm
          chmod +x astgen-linux
          chmod +x astgen-linux-arm
          gzexe astgen-linux
          gzexe astgen-linux-arm
          mv astgen-linux~ astgen-linux-uncompressed
          mv astgen-linux-arm~ astgen-linux-arm-uncompressed
      - name: Set next release version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
          files: |
            astgen-win.exe
            astgen-macos
            astgen-macos-arm
            astgen-linux
            astgen-linux-arm
            astgen-linux-uncompressed
            astgen-linux-arm-uncompressed
