name: release

on:
  push:
    branches: [master, main]
    tags: ["*"]

concurrency: production

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: astgen-linux
          - os: windows-latest
            artifact_name: astgen-win.exe
          - os: macos-latest
            artifact_name: astgen-macos
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'
      - name: Get next release version (dry run)
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      - name: Build
        run: |
          yarn install
          yarn build
          yarn bundle
      - name: Test
        run: |
          yarn test
      - name: Create Windows binaries
        if: matrix.os == 'windows-latest'
        run: |
          node --experimental-sea-config sea-config.json
          node -e "require('fs').copyFileSync(process.execPath, '${{ matrix.artifact_name }}')"
          npx postject ${{ matrix.artifact_name }} NODE_SEA_BLOB sea-prep.blob --overwrite --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
          cp .\bundle\astgen.js .
      - name: Create Linux binaries
        if: matrix.os == 'ubuntu-latest'
        run: |
          node --experimental-sea-config sea-config.json
          cp $(command -v node) ${{ matrix.artifact_name }}
          npx postject ${{ matrix.artifact_name }} NODE_SEA_BLOB sea-prep.blob --overwrite --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
          cp ./bundle/astgen.js .
      - name: Create MacOS binaries
        if: matrix.os == 'macos-latest'
        run: |
          node --experimental-sea-config sea-config.json
          cp $(command -v node) ${{ matrix.artifact_name }}
          codesign --remove-signature ${{ matrix.artifact_name }}
          npx postject ${{ matrix.artifact_name }} NODE_SEA_BLOB sea-prep.blob --overwrite --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 --macho-segment-name NODE_SEA
          codesign --sign - ${{ matrix.artifact_name }}
          cp ./bundle/astgen.js .
      - name: Set next release version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          overwrite: true
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: astgen*
          tag: ${{ steps.taggerDryRun.outputs.new_tag }}
